name: Build OpenNDS for OpenWRT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-opennds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup OpenWRT SDK
      run: |
        mkdir -p ~/openwrt-sdk
        cd ~/openwrt-sdk
        curl -LO https://downloads.openwrt.org/releases/24.10.2/targets/x86/64/openwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        tar -xf openwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        cd openwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libmicrohttpd-dev

    - name: Build OpenNDS
      run: |
        cd ~/openwrt-sdk/openwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64
        make deconfig
        make package/feeds/packages/opennds/compile V=s

    - name: Verify Compatibility
      run: |
        ldd ~/openwrt-sdk/openwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64/bin/packages/x86_64/base/opennds*.ipk | grep "libmicrohttpd.so.12"
