name: Build Coova-Chilli

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up OpenWrt SDK
      run: |
        # Download OpenWrt SDK for version 24.10
        wget https://downloads.openwrt.org/releases/24.10.0/targets/x86/64/openwrt-sdk-24.10.0-x86-64.tar.xz
        # Extract the SDK
        tar -xf openwrt-sdk-24.10.0-x86-64.tar.xz
        cd openwrt-sdk-24.10.0-x86-64

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libtool autoconf automake pkg-config libnl-genl-3-dev

    - name: Clone Coova-Chilli Repository
      run: |
        git clone https://github.com/coova/coova-chilli.git
        cd coova-chilli

    - name: Configure and Build Coova-Chilli
      run: |
        ./bootstrap
        ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-nft
        make
        make install

    - name: Archive Build Artifacts
      run: |
        tar -czvf coova-chilli-build.tar.gz /usr/local/sbin/chilli /etc/chilli

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coova-chilli-build
        path: coova-chilli-build.tar.gz
