name: Build openNDS v10.3.1 for ImmortalWrt 24.10.2 (x86_64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev \
            libssl-dev python3-distutils rsync unzip zlib1g-dev wget curl \
            xz-utils zstd

      - name: Download ImmortalWrt SDK
        run: |
          wget https://downloads.immortalwrt.org/releases/24.10.2/targets/x86/64/immortalwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar --use-compress-program=unzstd -xf immortalwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          mv immortalwrt-sdk-24.10.2-x86-64_gcc-13.3.0_musl.Linux-x86_64 sdk

      - name: Prepare opennds package
        run: |
          cd sdk/package
          mkdir opennds
          cd opennds
          wget https://github.com/openNDS/openNDS/archive/refs/tags/v10.3.1.zip
          unzip v10.3.1.zip
          mv openNDS-10.3.1/* .
          rm -rf v10.3.1.zip openNDS-10.3.1

          # Buat Makefile untuk opennds
          cat << 'EOF' > Makefile
          include $(TOPDIR)/rules.mk

          PKG_NAME:=opennds
          PKG_VERSION:=10.3.1
          PKG_RELEASE:=1

          PKG_SOURCE_URL:=https://github.com/openNDS/openNDS/archive/refs/tags
          PKG_SOURCE:=v$(PKG_VERSION).tar.gz
          PKG_HASH:=skip

          PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)

          include $(INCLUDE_DIR)/package.mk

          define Package/opennds
            SECTION:=net
            CATEGORY:=Network
            TITLE:=openNDS - Open Network Demarcation Service
            DEPENDS:=+libmicrohttpd-no-ssl
          endef

          define Package/opennds/description
            OpenNDS (Open Network Demarcation Service) - a high performance, small footprint Captive Portal.
          endef

          define Build/Compile
            $(MAKE) -C $(PKG_BUILD_DIR) \
              CC="$(TARGET_CC)" \
              CFLAGS="$(TARGET_CFLAGS)" \
              LDFLAGS="$(TARGET_LDFLAGS)"
          endef

          define Package/opennds/install
            $(INSTALL_DIR) $(1)/usr/sbin
            $(INSTALL_BIN) $(PKG_BUILD_DIR)/src/opennds $(1)/usr/sbin/
          endef

          $(eval $(call BuildPackage,opennds))
          EOF

      - name: Build package
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install libmicrohttpd-no-ssl
          make defconfig
          make package/opennds/compile V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opennds-10.3.1-ipk
          path: sdk/bin/packages/*/base/opennds_*.ipk
